CREATE TABLE IF NOT EXISTS advertising (
    id              VARCHAR(255) NOT NULL DEFAULT (UUID()),
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    image_url       VARCHAR(500),
    link_url        VARCHAR(500),
    position        ENUM('SIDEBAR_TOP','SIDEBAR_MIDDLE','SIDEBAR_BOTTOM','TOP_BANNER','BOTTOM_BANNER','POPUP') NOT NULL DEFAULT 'SIDEBAR_MIDDLE',
    is_active       TINYINT(1) NOT NULL DEFAULT 0,
    display_start   DATETIME,
    display_end     DATETIME,
    sort_order      INT NOT NULL DEFAULT 0,
    target_audience VARCHAR(50) NOT NULL DEFAULT 'ALL',
    clicks          INT NOT NULL DEFAULT 0,
    impressions     INT NOT NULL DEFAULT 0,
    payment_status  ENUM('PENDING','PAID','FREE') NOT NULL DEFAULT 'FREE',
    payment_amount  DECIMAL(10,2),
    payment_currency VARCHAR(10) DEFAULT 'FBU',
    created_by      VARCHAR(255),
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_advertising_position (position),
    INDEX idx_advertising_active (is_active, display_start, display_end),
    INDEX idx_advertising_sort (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
