-- V32: Add RIDE_REJECTED and SOS to notifications type ENUM
ALTER TABLE notifications
  MODIFY COLUMN type ENUM(
    'BOOKING','CANCELLATION','MESSAGE','REVIEW','SYSTEM',
    'PAYMENT','TRIP_UPDATE','IDENTITY_VERIFIED',
    'RIDE_REJECTED','SOS'
  ) NOT NULL;
