-- Ajouter RENDERED et ARCHIVED à l'ENUM MySQL de ride_requests.status
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE ride_requests
    MODIFY COLUMN status ENUM('SEARCHING','DRIVER_FOUND','ACCEPTED','DRIVER_EN_ROUTE','ARRIVED','IN_PROGRESS','COMPLETED','CANCELLED','EXPIRED','RENDERED','ARCHIVED') NOT NULL DEFAULT 'SEARCHING';

SET FOREIGN_KEY_CHECKS = 1;
