-- Ajouter RENDERED et ARCHIVED à l'ENUM MySQL de notifications.type
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE notifications
    MODIFY COLUMN type ENUM(
        'BOOKING','CANCELLATION','MESSAGE','REVIEW','SYSTEM',
        'PAYMENT','TRIP_UPDATE','IDENTITY_VERIFIED','RIDE_REJECTED',
        'SOS','RENDERED','ARCHIVED'
    ) NOT NULL;

SET FOREIGN_KEY_CHECKS = 1;
